In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credit = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
#Merging two dataset on tiltle
movies = movies.merge(credit, on='title')

In [6]:
movies.shape

(4809, 23)

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [9]:
#creating new dataframe with id,title, overview, genres, keywords, cast, crew
movies = movies[['id','title','overview','genres','keywords','cast','crew']]

In [10]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [12]:
#Droping null values
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.isna().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
#checking for duplicates values
movies.duplicated().sum()

0

In [16]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

<h2>Converting genres to a list</h2>

In [17]:
movies.genres[1]

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [18]:
import ast

In [19]:
def convert_genres_to_list(obj):
    genres_list = []
    for i in ast.literal_eval(obj):
        genres_list.append(i['name'])
    return genres_list

In [20]:
convert_genres_to_list(movies.genres[1])

['Adventure', 'Fantasy', 'Action']

In [21]:
movies.genres.apply(convert_genres_to_list)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [22]:
movies['genres'] = movies.genres.apply(convert_genres_to_list)

In [23]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
#Convert keywords to list
movies['keywords'] = movies.keywords.apply(convert_genres_to_list)

In [25]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [26]:
print(movies['cast'][0])

[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch's Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]

In [27]:
#We need to take the name of first 3 cast
def convert_cast_to_list(obj):
    cast_list = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter < 3:
            cast_list.append(i['name'])
            counter += 1
    return cast_list

In [28]:
convert_cast_to_list(movies['cast'][0])

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [29]:
movies.cast = movies.cast.apply(convert_cast_to_list)

In [30]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
#Fetch director name from crew

In [32]:
movies.crew[1]

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

In [33]:
# movies_crew_list = ast.literal_eval(movies.crew[1])
# movies_crew_list

def fetch_director_name_from_crew(obj):
    director_list = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            director_list.append(i['name'])
    return director_list

In [34]:
fetch_director_name_from_crew(movies.crew[1])

['Gore Verbinski']

In [35]:
movies.crew = movies.crew.apply(fetch_director_name_from_crew)

In [36]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
#Convert overview from string to list of words
movies.overview = movies.overview.apply(lambda x:x.split())

In [38]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [39]:
#removing all the spaces
movies.genres.apply(lambda x : [i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [40]:
movies.crew.isnull().sum()

0

In [41]:
movies.crew.apply(lambda x : [i.replace(" ","") for i in x])

0                              [JamesCameron]
1                             [GoreVerbinski]
2                                 [SamMendes]
3                          [ChristopherNolan]
4                             [AndrewStanton]
                        ...
4804                        [RobertRodriguez]
4805                            [EdwardBurns]
4806                             [ScottSmith]
4807                             [DanielHsia]
4808    [BrianHerzlinger, JonGunn, BrettWinn]
Name: crew, Length: 4806, dtype: object

In [42]:
movies['genres'] = movies.genres.apply(lambda x : [i.replace(" ","") for i in x])
movies['keywords'] = movies.keywords.apply(lambda x : [i.replace(" ","") for i in x])
movies['cast'] = movies.cast.apply(lambda x : [i.replace(" ","") for i in x])
movies['crew'] = movies.crew.apply(lambda x : [i.replace(" ","") for i in x])

In [43]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [44]:
#concadinating overview genres keywords cast crew into tag
movies['tags'] = movies.overview + movies.genres + movies.keywords + movies.cast + movies.crew

In [45]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [46]:
movies_df = movies[['id','title','tags']]

In [47]:
movies_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [48]:
#converting tag to string
movies_df.tags = movies_df.tags.apply(lambda x:" ".join(x))

C:\python_env\machine_learning_env\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [49]:
movies_df.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [50]:
movies_df.tags[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [51]:
#coverting tags to lower case
movies_df.tags = movies_df.tags.apply(lambda x: x.lower())

C:\python_env\machine_learning_env\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [57]:
movies_df.tags[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [59]:
#converting tags to its root words

In [60]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [61]:
ps.stem("loving")

'love'

In [62]:
def convert_to_root_words(text):
    word_list = []
    for i in text.split():
        word_list.append(ps.stem(i))
    return " ".join(word_list)

In [63]:
convert_to_root_words('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [64]:
movies_df.tags = movies_df.tags.apply(convert_to_root_words)

C:\python_env\machine_learning_env\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [66]:
vectors = cv.fit_transform(movies_df['tags']).toarray()

In [67]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [68]:
cv.get_feature_names()

C:\python_env\machine_learning_env\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 ...]

In [69]:
#finding cosine similarity between vectors

In [70]:
from sklearn.metrics.pairwise import cosine_similarity

In [71]:
cosine_similarity(vectors)

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [73]:
cosine_similarity(vectors).shape

(4806, 4806)

In [74]:
similarity = cosine_similarity(vectors)

In [76]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [77]:
#Get similar movies

In [82]:
movies_df[movies_df.title == 'Avatar'].index[0]

0

In [84]:
sorted(similarity[1],reverse=True)

[1.0,
 0.4140043409440133,
 0.27500954910846337,
 0.2533201985524494,
 0.20579830217101058,
 0.20579830217101058,
 0.18981415059132412,
 0.18499891602515212,
 0.17589669862367344,
 0.17503501050350123,
 0.17149858514250882,
 0.17149858514250882,
 0.17149858514250882,
 0.16647802295407294,
 0.16637806616154058,
 0.16502459049611234,
 0.16502459049611234,
 0.16477051091432687,
 0.16269784336399212,
 0.1618740515220081,
 0.1592324388246205,
 0.1592324388246205,
 0.1576320721888657,
 0.1569197342897824,
 0.15512630699850574,
 0.15339299776947407,
 0.15339299776947407,
 0.15339299776947407,
 0.15171652122725207,
 0.15158476564770806,
 0.15009383798227796,
 0.14969623771302393,
 0.14705882352941174,
 0.14705882352941174,
 0.14699878726500756,
 0.14699878726500756,
 0.1462544848254261,
 0.1449427589131121,
 0.1449427589131121,
 0.14134285422946366,
 0.14097096860865022,
 0.14097096860865022,
 0.140028008402801,
 0.140028008402801,
 0.1373087590952724,
 0.1355815361366601,
 0.1345345587992625,
 0.1345345587992625,
 0.13391789600139503,
 0.1332593209305539,
 0.1332593209305539,
 0.13284223283101426,
 0.13231403100624078,
 0.1320196723968899,
 0.1320196723968899,
 0.1320196723968899,
 0.13174886252731766,
 0.12964074471043285,
 0.12964074471043285,
 0.12964074471043283,
 0.12964074471043283,
 0.1292719224987548,
 0.1292719224987548,
 0.1292719224987548,
 0.12862393885688161,
 0.12862393885688161,
 0.12862393885688161,
 0.12862393885688161,
 0.1278274981412284,
 0.1278274981412284,
 0.12738595105969638,
 0.12738595105969638,
 0.12738595105969638,
 0.1264304343560434,
 0.1264304343560434,
 0.1264304343560434,
 0.12524485821702988,
 0.12524485821702988,
 0.12507819831856498,
 0.12507819831856498,
 0.12507819831856498,
 0.12478354962115543,
 0.12478354962115543,
 0.12478354962115543,
 0.12320822072673948,
 0.12320822072673948,
 0.12320822072673948,
 0.12126781251816647,
 0.12126781251816646,
 0.12126781251816646,
 0.12126781251816646,
 0.12065379433217113,
 0.12043434688555504,
 0.12007302660701852,
 0.12007302660701852,
 0.11961783342433499,
 0.11961783342433499,
 0.11941628680530642,
 0.11891287353862351,
 0.11803342130469503,
 0.11803342130469503,
 0.11778571185788639,
 0.11778571185788637,
 0.11778571185788637,
 0.11771773894935468,
 0.11764705882352938,
 0.11764705882352938,
 0.11764705882352938,
 0.11764705882352938,
 0.11764705882352938,
 0.11764705882352938,
 0.11726446574911562,
 0.11669000700233415,
 0.11669000700233413,
 0.11595420713048968,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11595420713048966,
 0.11577058990186095,
 0.11562432251572008,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11498609690941279,
 0.11458731212852641,
 0.1145873121285264,
 0.11433239009500587,
 0.11433239009500587,
 0.11363310286178552,
 0.11357771260606365,
 0.11357771260606365,
 0.11357771260606365,
 0.11357771260606365,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11227217828476795,
 0.11163607017227663,
 0.11128297681493143,
 0.1107018606925119,
 0.1107018606925119,
 0.11051407114136771,
 0.10984700727621793,
 0.10984700727621793,
 0.10984700727621793,
 0.10984700727621793,
 0.1097907187727647,
 0.1097907187727647,
 0.10969086361906959,
 0.10969086361906959,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10890171046725802,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.1080339539253607,
 0.1078676197944929,
 0.10727978097782273,
 0.10727978097782273,
 0.10727978097782273,
 0.10727978097782273,
 0.10718661571406801,
 0.10713431680111603,
 0.10713431680111603,
 0.10713431680111603,
 0.10585122480499262,
 0.10585122480499262,
 0.10585122480499262,
 0.10585122480499262,
 0.10585122480499262,
 0.10555008273018725,
 0.10502100630210075,
 0.10502100630210075,
 0.10502100630210075,
 0.10502100630210075,
 0.10502100630210075,
 0.10461315619318828,
 0.10461315619318828,
 0.10398629135096286,
 0.10341753799900383,
 0.10341753799900383,
 0.10341753799900383,
 0.10341753799900383,
 0.10341753799900383,
 0.10323001737691673,
 0.10289915108550529,
 0.10289915108550529,
 0.10289915108550529,
 0.10289915108550529,
 0.10289915108550529,
 0.10289915108550529,
 0.10226199851298272,
 0.10226199851298272,
 0.10226199851298272,
 0.10226199851298272,
 0.10176568762666317,
 0.10138954626279946,
 0.10114434748483471,
 0.10114434748483471,
 0.10114434748483471,
 0.10114434748483471,
 0.10114434748483471,
 0.10114434748483471,
 0.10090091909944687,
 0.10090091909944687,
 0.10090091909944687,
 0.10090091909944687,
 0.10090091909944687,
 0.10090091909944687,
 0.10090091909944687,
 0.10090091909944686,
 0.10036195573796253,
 0.10036195573796253,
 0.10006255865485197,
 0.10006255865485197,
 0.10006255865485197,
 0.10006255865485197,
 0.09968152785361249,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766743,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09901475429766741,
 0.09867967802605515,
 0.0983611844205792,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09799919151000504,
 0.09772038812426302,
 0.09737260471306503,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09723055853282464,
 0.09709195467257715,
 0.09701425001453318,
 0.09647549158488412,
 0.09647549158488411,
 0.09605842128561481,
 0.09605842128561481,
 0.09605842128561481,
 0.09605842128561481,
 0.09605842128561481,
 0.09605842128561481,
 0.09605842128561481,
 0.0958706236059213,
 0.0955394632947723,
 0.0955394632947723,
 0.09553946329477228,
 0.09553946329477228,
 0.09553946329477228,
 0.09553946329477228,
 0.09553946329477228,
 0.09553946329477228,
 0.09553946329477228,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09513029883089881,
 0.09469425238482124,
 0.0942285694863091,
 0.0942285694863091,
 0.0942285694863091,
 0.0942285694863091,
 0.09412207643723192,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.09356014857063996,
 0.09345802722104672,
 0.09335200560186731,
 0.09335200560186731,
 0.09335200560186731,
 0.09335200560186731,
 0.09335200560186731,
 0.09335200560186731,
 0.09249945801257606,
 0.09249945801257606,
 0.09249945801257606,
 0.09249945801257606,
 0.09249945801257606,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09240616554505461,
 0.09193289141911525,
 0.09166984970282112,
 0.09166984970282112,
 0.09166984970282112,
 0.09166984970282112,
 0.09166984970282112,
 0.09166984970282112,
 0.09166984970282112,
 0.0914090530158913,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09095085938862485,
 0.09086217008485092,
 0.09086217008485092,
 0.09086217008485092,
 0.09007546982220897,
 0.09007546982220897,
 0.09007546982220897,
 0.09007546982220897,
 0.09007546982220897,
 0.09007546982220897,
 0.09007546982220897,
 0.09007546982220897,
 0.08956221510397981,
 0.08956221510397981,
 0.08956221510397981,
 0.08956221510397981,
 0.08956221510397981,
 0.08956221510397981,
 0.08956221510397981,
 0.08956221510397981,
 0.08939981748151894,
 0.0893088561378213,
 0.0893088561378213,
 0.0893088561378213,
 0.0893088561378213,
 0.0893088561378213,
 0.08891787425369732,
 0.08889132764189396,
 0.08856148855400951,
 0.08856148855400951,
 0.08856148855400951,
 0.08856148855400951,
 0.08856148855400951,
 0.08856148855400951,
 0.08856148855400951,
 0.08856148855400951,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08823529411764704,
 0.08783257501821176,
 0.08783257501821176,
 0.08783257501821176,
 0.08751750525175062,
 0.08712136837380642,
 0.08712136837380642,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08696565534786725,
 0.08665671776277227,
 0.08642716314028856,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.0850871259623034,
 0.0850871259623034,
 0.0850871259623034,
 0.0850871259623034,
 0.0850871259623034,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.0844400661841498,
 0.0844400661841498,
 0.08380754741901122,
 0.08380754741901122,
 0.08380754741901122,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08346223261119858,
 0.08318903308077029,
 0.08318903308077029,
 0.08318903308077029,
 0.08318903308077029,
 0.08318903308077029,
 0.08318903308077029,
 0.08318903308077029,
 0.08258401390153339,
 0.08258401390153339,
 0.08258401390153339,
 0.08258401390153339,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08238525545716345,
 0.08213292636386628,
 0.08199200616907877,
 0.08141255010133054,
 0.08141255010133054,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08084520834544433,
 0.08035073760083702,
 0.08035073760083702,
 0.08035073760083702,
 0.08035073760083702,
 0.08035073760083702,
 0.08035073760083702,
 0.08035073760083702,
 0.08035073760083702,
 0.08028956459037002,
 0.08028956459037002,
 0.08028956459037002,
 0.07996162762590017,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07962575371800423,
 0.07961621941231024,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07938841860374446,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07868894753646336,
 0.07860624762130128,
 0.07845986714489121,
 0.07845986714489121,
 0.07845986714489121,
 0.07845986714489121,
 0.07845986714489121,
 0.07845986714489121,
 0.07845986714489121,
 0.07817631049941041,
 0.07817631049941041,
 0.07817631049941041,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07756315349925287,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07585826061362604,
 0.07585826061362604,
 0.07585826061362604,
 0.07585826061362604,
 0.07585826061362604,
 0.07585826061362604,
 0.07585826061362604,
 0.07585826061362604,
 0.07529766114978553,
 0.07529766114978553,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07504691899113898,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07484811885651196,
 0.07440653318043244,
 0.07440653318043244,
 0.07426106572325057,
 0.07426106572325057,
 0.07426106572325057,
 0.07426106572325057,
 0.07426106572325057,
 0.07426106572325057,
 0.07426106572325057,
 0.07426106572325057,
 0.07397267214553091,
 0.07397267214553091,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07349939363250378,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07276068751089988,
 0.07276068751089988,
 0.07276068751089988,
 0.07276068751089988,
 0.07276068751089988,
 0.07276068751089988,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07204381596421111,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07151985398521515,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07134772412317411,
 0.07075491376772249,
 0.07075491376772249,
 0.07067142711473183,
 0.07067142711473183,
 0.07067142711473183,
 0.07067142711473183,
 0.07067142711473183,
 0.07067142711473183,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.0700140042014005,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.06937459350943204,
 0.06937459350943204,
 0.06937459350943204,
 0.06937459350943204,
 0.06937459350943204,
 0.06875238727711584,
 0.06875238727711584,
 0.06875238727711584,
 0.06875238727711584,
 0.06875238727711584,
 0.06875238727711584,
 0.0686543795476362,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06859943405700353,
 0.06825898811407623,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06814662756363819,
 0.06792356108113244,
 0.06759303084186631,
 0.06755660236665673,
 0.06755660236665673,
 0.06755660236665673,
 0.06755660236665673,
 0.06755660236665673,
 0.06755660236665673,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06726727939963124,
 0.06698164210336598,
 0.06698164210336598,
 0.06698164210336598,
 0.06698164210336598,
 0.06698164210336598,
 0.06698164210336598,
 0.06698164210336598,
 0.06642111641550713,
 0.06642111641550713,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06600983619844494,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06587443126365883,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06534102628035482,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06482037235521643,
 0.06431196942844081,

In [94]:
sorted(list(enumerate(similarity[1])),reverse=True, key= lambda x: x[1])[1:6]

[(12, 0.4140043409440133),
 (199, 0.27500954910846337),
 (17, 0.2533201985524494),
 (216, 0.20579830217101058),
 (3572, 0.20579830217101058)]

In [98]:
def recomended_movie(movie):
    movie_index = movies_df[movies_df.title == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True, key= lambda x: x[1])[1:6]
    for i in movies_list:
        print(i[0])

In [99]:
recomended_movie('Avatar')

1216
2409
3730
507
539

In [102]:
movies_df.iloc[1216].title

'Aliens vs Predator: Requiem'

In [103]:
def recomended_movie(movie):
    movie_index = movies_df[movies_df.title == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True, key= lambda x: x[1])[1:6]
    for i in movies_list:
        print(movies_df.iloc[i[0]].title)

In [108]:
recomended_movie('The Avengers')

Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
Captain America: The First Avenger
Iron Man

In [109]:
import pickle

In [113]:
pickle.dump(movies_df.to_dict(),open('movie_dict.pkl', 'wb'))

In [114]:
pickle.dump(similarity,open('similarity.pkl','wb'))